---
language: python
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
cache: pip
sudo: false
before_install:
  - pip install pipenv --upgrade
install:
  - pipenv install --dev
script: pipenv run green -r -vvv
branches:
  only:
    - master
jobs:
  include:
    - stage: preflight
      python: '3.6'
      install:
        - pipenv install --dev
      script:
        # - pipenv check
        - yamllint . -s
        - pylama -v .
stages:
  - preflight
  - test
